"use client";
import Link from "next/link";
import { useState, useSyncExternalStore } from "react";
type Props={tenantId:string;slug:string;domain:string|null;site:{status:string;template:{code:string;name:string}|null;pages:Array<{isPublished:boolean}>}|null;settings:{platformName:string|null;logoUrl:string|null;heroImageUrl:string|null;primaryColor:string|null;secondaryColor:string|null;contactDetails:unknown}|null};
const subscribeToPort = () => () => {};
const obj=(v:unknown)=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
export function WebsitePanel({tenantId,slug,domain,site,settings}:Props){const contacts=obj(settings?.contactDetails);const [busy,setBusy]=useState(false);const localPort=useSyncExternalStore(subscribeToPort,()=>window.location.port||"3000",()=>"3000");const hostname=domain||`${slug}.localhost`;const preview=hostname.endsWith(".localhost")?`http://${hostname}:${localPort}`:`https://${hostname}`;
 async function publish(){setBusy(true);const r=await fetch(`/api/platform/tenants/${tenantId}/website`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"publish"})});setBusy(false);if(!r.ok)alert("Unable to publish website");else location.reload();}
 return <section className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold">Website</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${site?.status==='PUBLISHED'?'bg-emerald-500/10 text-emerald-600':'bg-amber-500/10 text-amber-600'}`}>{site?.status||'NOT INITIALIZED'}</span></div><p className="mt-1 text-sm text-[var(--color-muted)]">Managed presentation, branding and publishing for this academy.</p></div><div className="flex flex-wrap gap-2"><a href={preview} target="_blank" rel="noreferrer" className="rounded-lg border border-[var(--color-border)] px-3 py-2 text-xs font-bold">Preview Website</a><Link href={`/platform-admin/templates?tenantId=${tenantId}`} className="rounded-lg bg-[var(--color-primary)] px-3 py-2 text-xs font-bold text-white">{site?.template?'Change Template':'Choose Template'}</Link><button disabled={busy||!site} onClick={()=>void publish()} className="rounded-lg border border-[var(--color-primary)] px-3 py-2 text-xs font-bold text-[var(--color-primary)] disabled:opacity-50">Publish</button></div></div><dl className="mt-5 grid gap-4 border-t border-[var(--color-border)] pt-5 sm:grid-cols-4"><Item label="Current template" value={site?.template?.name||'—'}/><Item label="Primary domain" value={domain||`${slug}.localhost`}/><Item label="Brand color" value={settings?.primaryColor||'—'}/><Item label="WhatsApp" value={typeof contacts.whatsapp==='string'?contacts.whatsapp:'—'}/></dl></section>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-[var(--color-muted)]">{label}</dt><dd className="mt-1 truncate text-sm font-semibold">{value}</dd></div>}
