import { beforeEach,describe,expect,it,vi } from "vitest";
const spies=vi.hoisted(()=>({
  tx:vi.fn(),templateUpsert:vi.fn(),templateFind:vi.fn(),tenantFind:vi.fn(),siteFind:vi.fn(),siteUpdate:vi.fn(),siteCreate:vi.fn(),pageUpdate:vi.fn(),pageCreate:vi.fn(),sectionDelete:vi.fn(),sectionCreate:vi.fn(),settingsFind:vi.fn(),settingsUpsert:vi.fn(),auditCreate:vi.fn(),siteResult:vi.fn(),
}));
const transactionClient={site:{findUnique:spies.siteFind,update:spies.siteUpdate,create:spies.siteCreate},sitePage:{update:spies.pageUpdate,create:spies.pageCreate},pageSection:{deleteMany:spies.sectionDelete,createMany:spies.sectionCreate},tenantSettings:{findUnique:spies.settingsFind,upsert:spies.settingsUpsert},auditLog:{create:spies.auditCreate}};
vi.mock("@/lib/prisma",()=>({prisma:{websiteTemplate:{upsert:spies.templateUpsert,findUnique:spies.templateFind,findMany:vi.fn()},tenant:{findUnique:spies.tenantFind},$transaction:spies.tx,site:{findUnique:spies.siteResult}}}));
import { applyWebsiteTemplate } from "@/modules/sites/template-service";
const actor={userId:"user-platform",administratorId:"admin-platform"};

describe("platform template application",()=>{
 beforeEach(()=>{vi.clearAllMocks();spies.templateUpsert.mockReturnValue({});spies.tx.mockImplementation(async(value:unknown)=>Array.isArray(value)?value:(value as (tx:typeof transactionClient)=>unknown)(transactionClient));spies.tenantFind.mockResolvedValue({id:"tenant-a",name:"Alpha"});spies.templateFind.mockResolvedValue({id:"template-clean",code:"clean-education",version:1,isActive:true});spies.settingsFind.mockResolvedValue({contactDetails:{phone:"old"},socialLinks:{facebook:"https://example.com"}});spies.settingsUpsert.mockResolvedValue({});spies.auditCreate.mockResolvedValue({});spies.sectionCreate.mockResolvedValue({count:8});spies.siteUpdate.mockResolvedValue({id:"site-a"});spies.pageUpdate.mockResolvedValue({id:"page-a"});spies.siteResult.mockResolvedValue({id:"site-a"});});
 it("requires explicit platform-administrator authorization",async()=>{await expect(applyWebsiteTemplate({actor:null as never,tenantId:"tenant-a",templateCode:"clean-education"})).rejects.toThrow("PLATFORM_ADMIN_REQUIRED");expect(spies.tenantFind).not.toHaveBeenCalled();});
 it("rejects a missing tenant before any site mutation",async()=>{spies.tenantFind.mockResolvedValue(null);await expect(applyWebsiteTemplate({actor,tenantId:"missing",templateCode:"clean-education"})).rejects.toThrow("TENANT_NOT_FOUND");expect(spies.siteUpdate).not.toHaveBeenCalled();});
 it("rejects inactive templates",async()=>{spies.templateFind.mockResolvedValue({id:"template-clean",code:"clean-education",version:1,isActive:false});await expect(applyWebsiteTemplate({actor,tenantId:"tenant-a",templateCode:"clean-education"})).rejects.toThrow("TEMPLATE_INACTIVE");expect(spies.siteUpdate).not.toHaveBeenCalled();});
 it("is idempotent when the same template version is already initialized",async()=>{spies.siteFind.mockResolvedValue({id:"site-a",templateId:"template-clean",templateVersion:1,template:{code:"clean-education"},pages:[{id:"page-a",isHome:true,sections:[{type:"HERO",config:{title:"Owned"}}]}]});await applyWebsiteTemplate({actor,tenantId:"tenant-a",templateCode:"clean-education",initializeOnly:true});expect(spies.sectionDelete).not.toHaveBeenCalled();expect(spies.sectionCreate).not.toHaveBeenCalled();});
 it("switches presentation within the selected tenant and preserves semantic config",async()=>{spies.siteFind.mockResolvedValue({id:"site-a",templateId:"old",templateVersion:1,template:{code:"premium-dark"},pages:[{id:"page-a",isHome:true,isPublished:true,sections:[{type:"HERO",config:{title:"Tenant title"}}]}]});await applyWebsiteTemplate({actor,tenantId:"tenant-a",templateCode:"clean-education",publish:true});expect(spies.tenantFind).toHaveBeenCalledWith({where:{id:"tenant-a"},select:{id:true,name:true}});expect(spies.siteUpdate).toHaveBeenCalledWith(expect.objectContaining({where:{id:"site-a"},data:expect.objectContaining({templateId:"template-clean"})}));expect(spies.sectionCreate).toHaveBeenCalledWith({data:expect.arrayContaining([expect.objectContaining({pageId:"page-a",type:"HERO",variant:"calm",config:expect.objectContaining({title:"Tenant title"})})])});expect(spies.auditCreate).toHaveBeenCalledWith({data:expect.objectContaining({tenantId:"tenant-a",action:"SITE_TEMPLATE_CHANGED",metadata:expect.objectContaining({oldTemplate:"premium-dark",newTemplate:"clean-education"})})});});
});
