/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { ArrowUpRight, BookOpen, Check, Globe as Globe2, Video, Clock as Clock3, Users, Video as Monitor, MessageSquare as MessageCircle } from 'lucide-react';
import type { CSSProperties, ReactNode } from 'react';
import type { TenantPublicSettings } from '@/modules/settings/tenant-settings';
import type { Page, Course, Content } from './TemplateSiteRenderer';
import { trialLessonHref } from '@/modules/sites/trial-lesson';
import { readableBrandColor } from '@/modules/sites/brand-contrast';
import { AcademyLanguage } from './AcademyLanguage';
import './global-arabic.css';

const record = (v: unknown): Record<string, unknown> => v && typeof v === 'object' && !Array.isArray(v) ? v as Record<string, unknown> : {};
export function GlobalArabicSite({ page, settings, courses, content, locale, children }: { page: Page; settings: TenantPublicSettings; courses: Course[]; content: Content; locale: 'ar' | 'en'; children?: ReactNode }) {
  const ar = locale === 'ar';
  const tr = (en: string, arabic: string) => ar ? arabic : en;
  const text = (value: unknown, key: string) => { const r = record(value); return String(r[ar ? key : `${key}En`] ?? r[key] ?? ''); };
  const name = ar ? settings.platformName : settings.platformNameEn || settings.platformName;
  const cta = trialLessonHref(settings.contactDetails);
  const trial = tr('Book a Trial Lesson', 'احجز درسًا تجريبيًا');
  const demo = settings.tenantId === 'demo-tenant' || settings.tenantSlug === 'arabic-quran-demo';
  const button = <a className="aq-button" href={cta}>{trial}<ArrowUpRight size={18} aria-hidden /></a>;
  const nav = [['Home', 'الرئيسية', '/'], ['Programs', 'البرامج', '/#programs'], ['Teachers', 'المعلمون', '/#teachers'], ['How It Works', 'كيف نتعلم', '/#how-it-works'], ['About', 'عن الأكاديمية', '/#about'], ['FAQ', 'الأسئلة الشائعة', '/#faq']];
  const heading = (config: unknown) => <div className="aq-section-heading"><h2>{text(config, 'title')}</h2>{text(config, 'body') && <p>{text(config, 'body')}</p>}</div>;
  return <div className="aq-site" data-template="global-arabic-quran" dir={ar ? 'rtl' : 'ltr'} lang={locale} style={{ '--aq-green': readableBrandColor(settings.primaryColor || '#174f40'), '--aq-gold': settings.accentColor || '#b59967' } as CSSProperties}>
    {demo && <div className="aq-demo">{tr('DEMO ACADEMY · Sample profiles and learning content for preview', 'أكاديمية تجريبية · ملفات ومحتوى تعليمي للعرض فقط')}</div>}
    <header className="aq-header"><Link className="aq-brand" href="/">{settings.logoUrl ? <img src={settings.logoUrl} alt="" width={42} height={42} /> : <BookOpen size={34} strokeWidth={1.5} aria-hidden />}<span>{name}</span></Link>
      <nav className="aq-desktop-nav" aria-label={tr('Main navigation', 'التنقل الرئيسي')}>{nav.map(([en, arabic, href]) => <Link key={en} href={href}>{tr(en, arabic)}</Link>)}</nav>
      <AcademyLanguage locale={locale} /><Link className="aq-login" href="/login">{tr('Student Login', 'دخول الطالب')}</Link><span className="aq-header-cta">{button}</span>
      <details className="aq-mobile-nav"><summary>{tr('Menu', 'القائمة')}</summary><nav>{nav.map(([en, arabic, href]) => <Link key={en} href={href}>{tr(en, arabic)}</Link>)}<Link href="/login">{tr('Student Login', 'دخول الطالب')}</Link>{button}</nav></details>
    </header>
    {children ? <main className="aq-inner-page">{children}</main> : <main>{page.sections.map(section => {
      const config = record(section.config);
      const rows = Array.isArray(config.items) ? config.items : [];
      switch (section.type) {
        case 'HERO': return <section key={section.id} className="aq-hero aq-wrap"><div className="aq-hero-copy"><div className="aq-kicker"><span />{tr('A world of learning. A personal connection.', 'تعلّم بلا حدود، وتواصل شخصي.')}</div><h1>{text(config, 'title')}</h1><p>{text(config, 'body')}</p><div className="aq-actions">{button}<a className="aq-text-link" href="#programs">{tr('Explore Programs', 'استكشف البرامج')}<ArrowUpRight size={18} aria-hidden /></a></div><div className="aq-trust">{[[Video, tr('1-to-1 Lessons', 'دروس فردية')], [Clock3, tr('Flexible Schedule', 'مواعيد مرنة')], [Users, tr('Children & Adults', 'للأطفال والكبار')], [Globe2, tr('Learn From Anywhere', 'تعلّم من أي مكان')]].map(([Icon, label]) => { const I = Icon as typeof Video; return <span key={String(label)}><I size={17} aria-hidden />{String(label)}</span>; })}</div></div><div className="aq-hero-visual"><img className="aq-lesson-image" src={settings.heroImageUrl || '/academy/online-lesson.svg'} alt={tr('Online lesson visual placeholder', 'صورة توضيحية لدرس عبر الإنترنت')} width={640} height={560} />{demo && <figure className="aq-student-inset"><img src="/academy/student-lesson.webp" alt={tr('Fictional demo student in an online lesson', 'صورة طالب تجريبية في درس عبر الإنترنت')} width={150} height={150} /><figcaption>{tr('Demo lesson preview', 'معاينة درس تجريبي')}</figcaption></figure>}<div className="aq-lesson-label"><Video size={19} aria-hidden /><div><strong>{tr('Your space to learn', 'مساحتك للتعلّم')}</strong><span>{tr('One teacher. Your learning journey.', 'معلم يرشد رحلتك التعليمية.')}</span></div></div><div className="aq-progress-note"><Check size={17} aria-hidden />{tr('Small steps. Meaningful progress.', 'خطوات صغيرة وتقدّم ملموس.')}</div></div></section>;
        case 'COURSES': return <section id="programs" key={section.id} className="aq-wrap aq-section">{heading(config)}<div className="aq-programs">{courses.map((course, i) => <article className="aq-program" key={course.id}><Link href={`/courses/${course.slug}`} className={`aq-program-art aq-art-${i % 4}`}>{course.imageUrl ? <img src={course.imageUrl} alt="" loading="lazy" /> : <><span lang="ar">{['أ ب ت', 'اقرأ', 'ترتيل', 'حفظ'][i % 4]}</span><BookOpen size={28} strokeWidth={1} aria-hidden /></>}</Link><div className="aq-program-copy"><span className="aq-meta">{course.level || tr('Personal learning', 'تعلّم شخصي')}{course._count ? ` · ${course._count.lessons} ${tr('lessons', 'دروس')}` : ''}</span><h3><Link href={`/courses/${course.slug}`}>{ar ? course.titleAr || course.title : course.title}</Link></h3><p>{ar ? course.shortDesc : course.shortDescEn || course.shortDesc}</p>{course.createdById && <span className="aq-meta">{content.teachers.find(t => t.userId === course.createdById)?.name}</span>}{config.showPrices === true && <strong className="aq-price">{new Intl.NumberFormat(locale, { style: 'currency', currency: /^[A-Z]{3}$/.test(String(config.currency)) ? String(config.currency) : 'USD' }).format(Number(course.price) || 0)}</strong>}<Link className="aq-text-link" href={`/courses/${course.slug}`}>{tr('Explore program', 'استكشف البرنامج')}<ArrowUpRight size={18} aria-hidden /></Link></div></article>)}</div>{!courses.length && <p>{tr('New programs are being prepared. Contact us to find your learning path.', 'نعمل على إعداد برامج جديدة. تواصل معنا لاختيار مسارك.')}</p>}</section>;
        case 'FEATURES': return <section key={section.id} className="aq-learners"><div className="aq-wrap">{heading(config)}<div className="aq-audiences">{rows.map((row, i) => <div key={i}><span className="aq-number">0{i + 1}</span><h3>{text(row, 'title')}</h3><p>{text(row, 'body')}</p></div>)}</div></div></section>;
        case 'VIDEO': return <section id="how-it-works" key={section.id} className="aq-wrap aq-section">{heading(config)}<ol className="aq-steps">{rows.map((row, i) => <li key={i}><span>{i + 1}</span><h3>{text(row, 'title')}</h3><p>{text(row, 'body')}</p></li>)}</ol></section>;
        case 'CONTACT': return <section key={section.id} className="aq-private aq-wrap"><div className="aq-private-art"><span lang="ar">خطوة بخطوة</span><BookOpen size={64} strokeWidth={1} aria-hidden /><p>{tr('At your pace. With your teacher.', 'بالوتيرة المناسبة لك، مع معلمك.')}</p></div><div>{heading(config)}{button}</div></section>;
        case 'TEACHERS': return content.teachers.length ? <section id="teachers" key={section.id} className="aq-wrap aq-section">{heading(config)}<div className="aq-teachers">{content.teachers.map(teacher => <article key={teacher.id}><img src={teacher.teacherAvatarUrl || '/academy/teacher.svg'} alt={teacher.teacherAvatarUrl ? teacher.name : tr('Teacher illustration placeholder', 'رسم توضيحي للمعلم')} width={220} height={260} loading="lazy" /><div><span className="aq-meta">{tr('Meet your teacher', 'تعرّف على معلمك')}</span><h3>{teacher.name}</h3><p>{teacher.teacherSubject}</p>{teacher.languages && <p>{teacher.languages}</p>}{teacher.bio && <p>{teacher.bio}</p>}<a className="aq-text-link" href={cta}>{trial}<ArrowUpRight size={17} aria-hidden /></a></div></article>)}</div></section> : null;
        case 'ABOUT': return <section id="about" key={section.id} className="aq-family"><div className="aq-wrap aq-family-grid"><div>{heading(config)}</div><ul>{[[BookOpen, tr('Structured lessons & practice', 'دروس وتدريبات منظمة')], [Check, tr('Clear learning progress', 'تقدّم تعليمي واضح')], [MessageCircle, tr('Feedback from your teacher', 'ملاحظات من معلمك')], [Monitor, tr('Phone, tablet or laptop', 'الهاتف والجهاز اللوحي والحاسوب')]].map(([Icon, label]) => { const I = Icon as typeof BookOpen; return <li key={String(label)}><I size={22} aria-hidden />{String(label)}</li>; })}</ul></div></section>;
        case 'FAQ': return <section id="faq" key={section.id} className="aq-wrap aq-section aq-faq">{heading(config)}<div>{rows.map((row, i) => <details key={i}><summary>{text(row, 'title')}<span aria-hidden>+</span></summary><p>{text(row, 'body')}</p></details>)}</div></section>;
        case 'CTA': return <section key={section.id} className="aq-closing"><div className="aq-wrap">{heading(config)}{button}</div></section>;
        default: return null;
      }
    })}</main>}
    <footer id="academy-contact" className="aq-footer aq-wrap"><div><Link className="aq-brand" href="/"><BookOpen size={28} aria-hidden /><span>{name}</span></Link><p>{tr('A personal journey. A world of possibility.', 'رحلة شخصية وآفاق واسعة للتعلّم.')}</p></div><div><strong>{tr('Let’s find your next step', 'لنجد خطوتك التالية')}</strong>{cta !== '#academy-contact' ? <a href={cta}>{trial}</a> : <p>{tr('Trial booking opens when the academy adds its contact details.', 'يبدأ الحجز عند إضافة بيانات التواصل مع الأكاديمية.')}</p>}<Link href="/login">{tr('Student Login', 'دخول الطالب')}</Link></div><small>Powered by NexaClass{demo ? ' · DEMO' : ''}</small></footer>
  </div>;
}



